steps:
  # 1. Build the container image using automatic Container Registry (gcr.io)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/remix-uad36-qc-beta:$COMMIT_SHA', '.']

  # 2. Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/remix-uad36-qc-beta:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'remix-uad36-qc-beta'
      - '--image'
      - 'gcr.io/$PROJECT_ID/remix-uad36-qc-beta:$COMMIT_SHA'
      - '--region'
      - 'us-east1'

options:
  logging: CLOUD_LOGGING_ONLY
